=== BD2KGenomics/dcc-metadata-indexer/metadata_schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "metadata_schema@0.0.2",
    "description": "metadata record for a donor",
    "type": "object",
    "definitions": {},
    "required": ["program", "project", "center_name", "submitter_donor_id", "donor_uuid", "schema_version", "timestamp", "specimen"],
    "properties": {
        "program": {
            "type": "string"
        },
        "project": {
            "type": "string"
        },
        "center_name": {
            "type": "string"
        },
        "submitter_donor_id": {
            "type": "string"
        },
        "donor_uuid": {
            "type": "string"
        },
        "schema_version": {
            "type": "string"
        },
        "timestamp": {
            "type": "string"
        },
        "specimen": {
            "type": "array",
            "items": {
                "type": "object",
                "required": ["submitter_specimen_id", "specimen_uuid", "submitter_specimen_type", "samples"],
                "properties": {
                    "submitter_specimen_id": {
                        "type": "string"
                    },
                    "specimen_uuid": {
                        "type": "string"
                    },
                    "submitter_specimen_type": {
                        "type": "string"
                    },
                    "samples": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "required": ["submitter_sample_id", "sample_uuid", "analysis"],
                            "properties": {
                                "submitter_sample_id": {
                                    "type": "string"
                                },
                                "sample_uuid": {
                                    "type": "string"
                                },
                                "analysis": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "required": ["analysis_type", "bundle_uuid", "workflow_name", "workflow_version", "workflow_outputs"],
                                        "properties": {
                                            "analysis_type": {
                                                "type": "string"
                                            },
                                            "bundle_uuid": {
                                                "type": "string"
                                            },
                                            "workflow_name": {
                                                "type": "string"
                                            },
                                            "workflow_version": {
                                                "type": "string"
                                            },
                                            "workflow_outputs": {
                                                "type": "array",
                                                "items": {
                                                    "type": "object",
                                                    "required": ["file_path", "file_type"],
                                                    "properties": {
                                                        "file_path": {
                                                            "type": "string"
                                                        },
                                                        "file_type": {
                                                            "type": "string"
                                                        },
                                                        "file_uuid": {
                                                            "type": "string"
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

=== BD2KGenomics/dcc-metadata-indexer/output_metadata_7_20/2d49242e-b8f9-50ff-b304-158588382735/metadata.json
{
    "center_name": "Stanford",
    "donor_uuid": "088bda20-30d2-5944-a5fd-fee9a223f1a7",
    "program": "TEST",
    "project": "TEST",
    "schema_version": "0.0.2",
    "specimen": [
        {
            "samples": [
                {
                    "analysis": [
                        {
                            "analysis_type": "alignment",
                            "bundle_uuid": "2d49242e-b8f9-50ff-b304-158588382735",
                            "workflow_name": "bwa-mem-aligner",
                            "workflow_outputs": [
                                {
                                    "file_path": "sample_upload_files/tumor.bam",
                                    "file_type": "bam"
                                }
                            ],
                            "workflow_version": "1.2.1"
                        }
                    ],
                    "sample_uuid": "8f2f5091-a6de-5b05-a2b1-331f582f4b41",
                    "submitter_sample_id": "S123472b1"
                }
            ],
            "specimen_uuid": "2d352c29-f993-57cd-9e8b-bb73909c1dbb",
            "submitter_specimen_id": "S123472b",
            "submitter_specimen_type": "Primary tumour - solid tissue"
        }
    ],
    "submitter_donor_id": "S123472",
    "timestamp": "2016-07-20T21:39:38.985491"
}

=== BD2KGenomics/dcc-metadata-indexer/output_metadata_7_20/314ae2cb-3ae4-578c-9a5c-ec414f6eeb6e/metadata.json
{
    "center_name": "Stanford",
    "donor_uuid": "dc123cfd-6e09-5635-b81f-bce781244892",
    "program": "TEST",
    "project": "TEST",
    "schema_version": "0.0.2",
    "specimen": [
        {
            "samples": [
                {
                    "analysis": [
                        {
                            "analysis_type": "germline_variant_calling",
                            "bundle_uuid": "314ae2cb-3ae4-578c-9a5c-ec414f6eeb6e",
                            "workflow_name": "germline-gatk",
                            "workflow_outputs": [
                                {
                                    "file_path": "sample_upload_files/germline.vcf",
                                    "file_type": "vcf"
                                }
                            ],
                            "workflow_version": "2.1.1"
                        }
                    ],
                    "sample_uuid": "942b29a5-d0f8-5a80-a3b1-e9a8a50363f5",
                    "submitter_sample_id": "S368291a1"
                }
            ],
            "specimen_uuid": "9a5a1dd7-7ed6-5c52-b86e-71c6e2d4a156",
            "submitter_specimen_id": "S368291a",
            "submitter_specimen_type": "Normal - blood derived"
        }
    ],
    "submitter_donor_id": "S368291",
    "timestamp": "2016-07-20T21:39:38.985910"
}

=== BD2KGenomics/dcc-metadata-indexer/output_metadata_7_20/84e9bb68-6109-5f57-9f25-b2421d3bc2f6/metadata.json
{
    "center_name": "Stanford",
    "donor_uuid": "088bda20-30d2-5944-a5fd-fee9a223f1a7",
    "program": "TEST",
    "project": "TEST",
    "schema_version": "0.0.2",
    "specimen": [
        {
            "samples": [
                {
                    "analysis": [
                        {
                            "analysis_type": "rna_seq_quantification",
                            "bundle_uuid": "84e9bb68-6109-5f57-9f25-b2421d3bc2f6",
                            "workflow_name": "rnaseq-cgl",
                            "workflow_outputs": [
                                {
                                    "file_path": "sample_upload_files/gene_expression.rsem",
                                    "file_type": "rsem"
                                }
                            ],
                            "workflow_version": "3.2.1"
                        }
                    ],
                    "sample_uuid": "8f2f5091-a6de-5b05-a2b1-331f582f4b41",
                    "submitter_sample_id": "S123472b1"
                }
            ],
            "specimen_uuid": "2d352c29-f993-57cd-9e8b-bb73909c1dbb",
            "submitter_specimen_id": "S123472b",
            "submitter_specimen_type": "Primary tumour - solid tissue"
        }
    ],
    "submitter_donor_id": "S123472",
    "timestamp": "2016-07-20T21:39:38.985520"
}

=== BD2KGenomics/dcc-metadata-indexer/output_metadata_7_20/7e39efc2-b12a-5d62-9542-8bbd5d4715c9/metadata.json
{
    "center_name": "Stanford",
    "donor_uuid": "5e6233fb-f193-59da-8102-b073a370a94f",
    "program": "TEST",
    "project": "TEST",
    "schema_version": "0.0.2",
    "specimen": [
        {
            "samples": [
                {
                    "analysis": [
                        {
                            "analysis_type": "germline_variant_calling",
                            "bundle_uuid": "7e39efc2-b12a-5d62-9542-8bbd5d4715c9",
                            "workflow_name": "germline-gatk",
                            "workflow_outputs": [
                                {
                                    "file_path": "sample_upload_files/germline.vcf",
                                    "file_type": "vcf"
                                }
                            ],
                            "workflow_version": "2.1.1"
                        }
                    ],
                    "sample_uuid": "5d4f790c-e079-5f17-b9d7-f7d24a552a55",
                    "submitter_sample_id": "S191920a1"
                }
            ],
            "specimen_uuid": "67ecf138-52ef-5e6a-b96b-b41320209a5b",
            "submitter_specimen_id": "S191920a",
            "submitter_specimen_type": "Normal - blood derived"
        }
    ],
    "submitter_donor_id": "S191920",
    "timestamp": "2016-07-20T21:39:38.985559"
}

=== BD2KGenomics/dcc-metadata-indexer/output_metadata_7_20/d473de7b-0258-5f9a-bf38-7ddb794fe58d/metadata.json
{
    "center_name": "Stanford",
    "donor_uuid": "b121a26b-282c-5830-9084-c3b74bb56fc0",
    "program": "TEST",
    "project": "TEST",
    "schema_version": "0.0.2",
    "specimen": [
        {
            "samples": [
                {
                    "analysis": [
                        {
                            "analysis_type": "somatic_variant_calling",
                            "bundle_uuid": "d473de7b-0258-5f9a-bf38-7ddb794fe58d",
                            "workflow_name": "pcawg_sanger_workflow",
                            "workflow_outputs": [
                                {
                                    "file_path": "sample_upload_files/somatic.snv.vcf",
                                    "file_type": "vcf"
                                },
                                {
                                    "file_path": "sample_upload_files/somatic.indel.vcf",
                                    "file_type": "vcf"
                                }
                            ],
                            "workflow_version": "2.9.9"
                        }
                    ],
                    "sample_uuid": "a8f34297-27a0-5609-bd62-0d8b8872dea2",
                    "submitter_sample_id": "S917367b1"
                }
            ],
            "specimen_uuid": "fcd4a069-e881-59a1-a506-d8ec1071a9c8",
            "submitter_specimen_id": "S917367b",
            "submitter_specimen_type": "Primary tumour - solid tissue"
        }
    ],
    "submitter_donor_id": "S917367",
    "timestamp": "2016-07-20T21:39:38.985688"
}

=== BD2KGenomics/dcc-metadata-indexer/output_metadata_7_20/ca3ccf42-c0ea-553b-b19f-e34570a1f03c/metadata.json
{
    "center_name": "Stanford",
    "donor_uuid": "088bda20-30d2-5944-a5fd-fee9a223f1a7",
    "program": "TEST",
    "project": "TEST",
    "schema_version": "0.0.2",
    "specimen": [
        {
            "samples": [
                {
                    "analysis": [
                        {
                            "analysis_type": "sequence_upload",
                            "bundle_uuid": "ca3ccf42-c0ea-553b-b19f-e34570a1f03c",
                            "workflow_name": "Sequence Uploader",
                            "workflow_outputs": [
                                {
                                    "file_path": "sample_upload_files/normal.fastq.gz",
                                    "file_type": "fastq"
                                }
                            ],
                            "workflow_version": "1.0.0"
                        }
                    ],
                    "sample_uuid": "0c34704b-dd86-5141-aaf0-573656dee389",
                    "submitter_sample_id": "S123472a1"
                }
            ],
            "specimen_uuid": "03a781e4-e6a9-5d61-861e-49fcd034c5e4",
            "submitter_specimen_id": "S123472a",
            "submitter_specimen_type": "Normal - blood derived"
        }
    ],
    "submitter_donor_id": "S123472",
    "timestamp": "2016-07-20T21:39:38.985462"
}

=== BD2KGenomics/dcc-metadata-indexer/output_metadata_7_20/d020ba5a-e38e-5ecb-ac3a-226cffa04b3b/metadata.json
{
    "center_name": "Stanford",
    "donor_uuid": "5e6233fb-f193-59da-8102-b073a370a94f",
    "program": "TEST",
    "project": "TEST",
    "schema_version": "0.0.2",
    "specimen": [
        {
            "samples": [
                {
                    "analysis": [
                        {
                            "analysis_type": "alignment",
                            "bundle_uuid": "d020ba5a-e38e-5ecb-ac3a-226cffa04b3b",
                            "workflow_name": "bwa-mem-aligner",
                            "workflow_outputs": [
                                {
                                    "file_path": "sample_upload_files/tumor.bam",
                                    "file_type": "bam"
                                }
                            ],
                            "workflow_version": "1.2.1"
                        }
                    ],
                    "sample_uuid": "7f1f6df6-9719-51c8-b82d-8e121e3d1d31",
                    "submitter_sample_id": "S191920b1"
                }
            ],
            "specimen_uuid": "6ec0271a-a40d-5813-97ab-7d0582fccf35",
            "submitter_specimen_id": "S191920b",
            "submitter_specimen_type": "Primary tumour - solid tissue"
        }
    ],
    "submitter_donor_id": "S191920",
    "timestamp": "2016-07-20T21:39:38.985552"
}

=== BD2KGenomics/dcc-metadata-indexer/output_metadata_7_20/6f50c297-72c9-582c-8434-5cee55bd76c5/metadata.json
{
    "center_name": "Stanford",
    "donor_uuid": "0f1d53cb-9ef8-58ba-8db6-4eae42ee4316",
    "program": "TEST",
    "project": "TEST",
    "schema_version": "0.0.2",
    "specimen": [
        {
            "samples": [
                {
                    "analysis": [
                        {
                            "analysis_type": "alignment",
                            "bundle_uuid": "6f50c297-72c9-582c-8434-5cee55bd76c5",
                            "workflow_name": "bwa-mem-aligner",
                            "workflow_outputs": [
                                {
                                    "file_path": "sample_upload_files/normal.bam",
                                    "file_type": "bam"
                                }
                            ],
                            "workflow_version": "1.2.1"
                        }
                    ],
                    "sample_uuid": "efd00a1d-604e-5e65-bf88-1c1464f14faa",
                    "submitter_sample_id": "S627291a1"
                }
            ],
            "specimen_uuid": "92511bd2-d5d8-51f4-8c0c-1cb53d54c6bf",
            "submitter_specimen_id": "S627291a",
            "submitter_specimen_type": "Normal - blood derived"
        }
    ],
    "submitter_donor_id": "S627291",
    "timestamp": "2016-07-20T21:39:38.985722"
}
