=== BD2KGenomics/dcc-metadata-indexer/metadata_schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "metadata_schema@0.0.2",
    "description": "metadata record for a donor",
    "type": "object",
    "definitions": {},
    "required": ["program", "project", "center_name", "submitter_donor_id", "donor_uuid", "schema_version", "timestamp", "specimen"],
    "properties": {
        "program": {
            "type": "string"
        },
        "project": {
            "type": "string"
        },
        "center_name": {
            "type": "string"
        },
        "submitter_donor_id": {
            "type": "string"
        },
        "donor_uuid": {
            "type": "string"
        },
        "schema_version": {
            "type": "string"
        },
        "timestamp": {
            "type": "string"
        },
        "specimen": {
            "type": "array",
            "items": {
                "type": "object",
                "required": ["submitter_specimen_id", "specimen_uuid", "submitter_specimen_type", "samples"],
                "properties": {
                    "submitter_specimen_id": {
                        "type": "string"
                    },
                    "specimen_uuid": {
                        "type": "string"
                    },
                    "submitter_specimen_type": {
                        "type": "string"
                    },
                    "samples": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "required": ["submitter_sample_id", "sample_uuid", "analysis"],
                            "properties": {
                                "submitter_sample_id": {
                                    "type": "string"
                                },
                                "sample_uuid": {
                                    "type": "string"
                                },
                                "analysis": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "required": ["analysis_type", "bundle_uuid", "workflow_name", "workflow_version", "workflow_outputs"],
                                        "properties": {
                                            "analysis_type": {
                                                "type": "string"
                                            },
                                            "bundle_uuid": {
                                                "type": "string"
                                            },
                                            "workflow_name": {
                                                "type": "string"
                                            },
                                            "workflow_version": {
                                                "type": "string"
                                            },
                                            "workflow_outputs": {
                                                "type": "array",
                                                "items": {
                                                    "type": "object",
                                                    "required": ["file_path", "file_type"],
                                                    "properties": {
                                                        "file_path": {
                                                            "type": "string"
                                                        },
                                                        "file_type": {
                                                            "type": "string"
                                                        },
                                                        "file_uuid": {
                                                            "type": "string"
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

=== BD2KGenomics/dcc-metadata-indexer/output_metadata_7_20/5c58e075-a2ba-536c-b039-f0418746dcea/metadata.json
{
    "center_name": "Stanford",
    "donor_uuid": "088bda20-30d2-5944-a5fd-fee9a223f1a7",
    "program": "TEST",
    "project": "TEST",
    "schema_version": "0.0.2",
    "specimen": [
        {
            "samples": [
                {
                    "analysis": [
                        {
                            "analysis_type": "sequence_upload",
                            "bundle_uuid": "5c58e075-a2ba-536c-b039-f0418746dcea",
                            "workflow_name": "Sequence Uploader",
                            "workflow_outputs": [
                                {
                                    "file_path": "sample_upload_files/tumor.fastq.gz",
                                    "file_type": "fastq"
                                }
                            ],
                            "workflow_version": "1.0.0"
                        }
                    ],
                    "sample_uuid": "8f2f5091-a6de-5b05-a2b1-331f582f4b41",
                    "submitter_sample_id": "S123472b1"
                }
            ],
            "specimen_uuid": "2d352c29-f993-57cd-9e8b-bb73909c1dbb",
            "submitter_specimen_id": "S123472b",
            "submitter_specimen_type": "Primary tumour - solid tissue"
        }
    ],
    "submitter_donor_id": "S123472",
    "timestamp": "2016-07-20T21:39:38.985476"
}

=== BD2KGenomics/dcc-metadata-indexer/test_output/088148493495402847502/a_meta04.json
{
  "center_name": "Stanford",
  "donor_uuid": "088bda20-30d2-5944-a5fd-fee9a223f1a7",
  "program": "TEST",
  "project": "TEST",
  "schema_version": "0.0.1",
  "specimen": [
    {
      "samples": [
        {
          "analysis": [{
            "analysis_type": "sequence_upload",
            "bundle_uuid": "697e0740-d302-5699-b4fb-04c3352565c8",
            "workflow_name": "Sequence Uploader",
            "workflow_outputs": [
              {
                "file_path": "sample_upload_files/tumor.bam",
                "file_type": "bam",
                "file_uuid": "15adb41a-f0ee-5334-994e-0641d8eb9beb"
              }
            ],
            "workflow_version": "1.0.2",
	    "timestamp": "2016-07-19T17:13:30.491517"
          }],
          "sample_uuid": "8f2f5091-a6de-5b05-a2b1-331f582f4b41",
          "submitter_sample_id": "S123472b1"
        }
      ],
      "specimen_uuid": "2d352c29-f993-57cd-9e8b-bb73909c1dbb",
      "submitter_specimen_id": "S123472b",
      "submitter_specimen_type": "Primary tumour - solid tissue"
    }
  ],
  "submitter_donor_id": "S123472",
  "timestamp": "2016-07-19T17:13:37.491517"
}

=== BD2KGenomics/dcc-metadata-indexer/output_metadata_7_20/c1b6f53b-d682-5592-984c-76c9a7051f7d/metadata.json
{
    "center_name": "Stanford",
    "donor_uuid": "b121a26b-282c-5830-9084-c3b74bb56fc0",
    "program": "TEST",
    "project": "TEST",
    "schema_version": "0.0.2",
    "specimen": [
        {
            "samples": [
                {
                    "analysis": [
                        {
                            "analysis_type": "sequence_upload",
                            "bundle_uuid": "c1b6f53b-d682-5592-984c-76c9a7051f7d",
                            "workflow_name": "Sequence Uploader",
                            "workflow_outputs": [
                                {
                                    "file_path": "sample_upload_files/tumor.fastq.gz",
                                    "file_type": "fastq"
                                }
                            ],
                            "workflow_version": "1.0.0"
                        }
                    ],
                    "sample_uuid": "a8f34297-27a0-5609-bd62-0d8b8872dea2",
                    "submitter_sample_id": "S917367b1"
                }
            ],
            "specimen_uuid": "fcd4a069-e881-59a1-a506-d8ec1071a9c8",
            "submitter_specimen_id": "S917367b",
            "submitter_specimen_type": "Primary tumour - solid tissue"
        }
    ],
    "submitter_donor_id": "S917367",
    "timestamp": "2016-07-20T21:39:38.985652"
}

=== BD2KGenomics/dcc-metadata-indexer/output_metadata_7_20/433c5ef9-e4db-5602-923c-1d454a9baad5/metadata.json
{
    "center_name": "Stanford",
    "donor_uuid": "0f1d53cb-9ef8-58ba-8db6-4eae42ee4316",
    "program": "TEST",
    "project": "TEST",
    "schema_version": "0.0.2",
    "specimen": [
        {
            "samples": [
                {
                    "analysis": [
                        {
                            "analysis_type": "sequence_upload",
                            "bundle_uuid": "433c5ef9-e4db-5602-923c-1d454a9baad5",
                            "workflow_name": "Sequence Uploader",
                            "workflow_outputs": [
                                {
                                    "file_path": "sample_upload_files/normal.fastq.gz",
                                    "file_type": "fastq"
                                }
                            ],
                            "workflow_version": "1.0.0"
                        }
                    ],
                    "sample_uuid": "efd00a1d-604e-5e65-bf88-1c1464f14faa",
                    "submitter_sample_id": "S627291a1"
                }
            ],
            "specimen_uuid": "92511bd2-d5d8-51f4-8c0c-1cb53d54c6bf",
            "submitter_specimen_id": "S627291a",
            "submitter_specimen_type": "Normal - blood derived"
        }
    ],
    "submitter_donor_id": "S627291",
    "timestamp": "2016-07-20T21:39:38.985705"
}

=== BD2KGenomics/dcc-metadata-indexer/output_metadata_7_20/854d1130-e1fc-57d8-bd93-9e38831e334d/metadata.json
{
    "center_name": "Stanford",
    "donor_uuid": "088bda20-30d2-5944-a5fd-fee9a223f1a7",
    "program": "TEST",
    "project": "TEST",
    "schema_version": "0.0.2",
    "specimen": [
        {
            "samples": [
                {
                    "analysis": [
                        {
                            "analysis_type": "alignment",
                            "bundle_uuid": "854d1130-e1fc-57d8-bd93-9e38831e334d",
                            "workflow_name": "bwa-mem-aligner",
                            "workflow_outputs": [
                                {
                                    "file_path": "sample_upload_files/normal.bam",
                                    "file_type": "bam"
                                }
                            ],
                            "workflow_version": "1.2.1"
                        }
                    ],
                    "sample_uuid": "0c34704b-dd86-5141-aaf0-573656dee389",
                    "submitter_sample_id": "S123472a1"
                }
            ],
            "specimen_uuid": "03a781e4-e6a9-5d61-861e-49fcd034c5e4",
            "submitter_specimen_id": "S123472a",
            "submitter_specimen_type": "Normal - blood derived"
        }
    ],
    "submitter_donor_id": "S123472",
    "timestamp": "2016-07-20T21:39:38.985484"
}

=== BD2KGenomics/dcc-metadata-indexer/output_metadata_7_20/a21dac21-f49f-556a-b463-859a66d8d0f5/metadata.json
{
    "center_name": "Stanford",
    "donor_uuid": "b121a26b-282c-5830-9084-c3b74bb56fc0",
    "program": "TEST",
    "project": "TEST",
    "schema_version": "0.0.2",
    "specimen": [
        {
            "samples": [
                {
                    "analysis": [
                        {
                            "analysis_type": "alignment",
                            "bundle_uuid": "a21dac21-f49f-556a-b463-859a66d8d0f5",
                            "workflow_name": "bwa-mem-aligner",
                            "workflow_outputs": [
                                {
                                    "file_path": "sample_upload_files/tumor.bam",
                                    "file_type": "bam"
                                }
                            ],
                            "workflow_version": "1.2.1"
                        }
                    ],
                    "sample_uuid": "a8f34297-27a0-5609-bd62-0d8b8872dea2",
                    "submitter_sample_id": "S917367b1"
                }
            ],
            "specimen_uuid": "fcd4a069-e881-59a1-a506-d8ec1071a9c8",
            "submitter_specimen_id": "S917367b",
            "submitter_specimen_type": "Primary tumour - solid tissue"
        }
    ],
    "submitter_donor_id": "S917367",
    "timestamp": "2016-07-20T21:39:38.985671"
}

=== BD2KGenomics/dcc-metadata-indexer/output_metadata_7_20/231ecfb1-5dd2-5368-9413-dedcc4a05d19/metadata.json
{
    "center_name": "Stanford",
    "donor_uuid": "5e6233fb-f193-59da-8102-b073a370a94f",
    "program": "TEST",
    "project": "TEST",
    "schema_version": "0.0.2",
    "specimen": [
        {
            "samples": [
                {
                    "analysis": [
                        {
                            "analysis_type": "sequence_upload",
                            "bundle_uuid": "231ecfb1-5dd2-5368-9413-dedcc4a05d19",
                            "workflow_name": "Sequence Uploader",
                            "workflow_outputs": [
                                {
                                    "file_path": "sample_upload_files/tumor.fastq.gz",
                                    "file_type": "fastq"
                                }
                            ],
                            "workflow_version": "1.0.0"
                        }
                    ],
                    "sample_uuid": "7f1f6df6-9719-51c8-b82d-8e121e3d1d31",
                    "submitter_sample_id": "S191920b1"
                }
            ],
            "specimen_uuid": "6ec0271a-a40d-5813-97ab-7d0582fccf35",
            "submitter_specimen_id": "S191920b",
            "submitter_specimen_type": "Primary tumour - solid tissue"
        }
    ],
    "submitter_donor_id": "S191920",
    "timestamp": "2016-07-20T21:39:38.985534"
}

=== BD2KGenomics/dcc-metadata-indexer/output_metadata_7_20/af23de4e-7599-53ea-b0de-9a9a042079c7/metadata.json
{
    "center_name": "Stanford",
    "donor_uuid": "5e6233fb-f193-59da-8102-b073a370a94f",
    "program": "TEST",
    "project": "TEST",
    "schema_version": "0.0.2",
    "specimen": [
        {
            "samples": [
                {
                    "analysis": [
                        {
                            "analysis_type": "rna_seq_quantification",
                            "bundle_uuid": "af23de4e-7599-53ea-b0de-9a9a042079c7",
                            "workflow_name": "rnaseq-cgl",
                            "workflow_outputs": [
                                {
                                    "file_path": "sample_upload_files/gene_expression.rsem",
                                    "file_type": "rsem"
                                }
                            ],
                            "workflow_version": "3.2.1"
                        }
                    ],
                    "sample_uuid": "7f1f6df6-9719-51c8-b82d-8e121e3d1d31",
                    "submitter_sample_id": "S191920b1"
                }
            ],
            "specimen_uuid": "6ec0271a-a40d-5813-97ab-7d0582fccf35",
            "submitter_specimen_id": "S191920b",
            "submitter_specimen_type": "Primary tumour - solid tissue"
        }
    ],
    "submitter_donor_id": "S191920",
    "timestamp": "2016-07-20T21:39:38.985576"
}
