=== BD2KGenomics/dcc-metadata-indexer/metadata_schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "metadata_schema@0.0.2",
    "description": "metadata record for a donor",
    "type": "object",
    "definitions": {},
    "required": ["program", "project", "center_name", "submitter_donor_id", "donor_uuid", "schema_version", "timestamp", "specimen"],
    "properties": {
        "program": {
            "type": "string"
        },
        "project": {
            "type": "string"
        },
        "center_name": {
            "type": "string"
        },
        "submitter_donor_id": {
            "type": "string"
        },
        "donor_uuid": {
            "type": "string"
        },
        "schema_version": {
            "type": "string"
        },
        "timestamp": {
            "type": "string"
        },
        "specimen": {
            "type": "array",
            "items": {
                "type": "object",
                "required": ["submitter_specimen_id", "specimen_uuid", "submitter_specimen_type", "samples"],
                "properties": {
                    "submitter_specimen_id": {
                        "type": "string"
                    },
                    "specimen_uuid": {
                        "type": "string"
                    },
                    "submitter_specimen_type": {
                        "type": "string"
                    },
                    "samples": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "required": ["submitter_sample_id", "sample_uuid", "analysis"],
                            "properties": {
                                "submitter_sample_id": {
                                    "type": "string"
                                },
                                "sample_uuid": {
                                    "type": "string"
                                },
                                "analysis": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "required": ["analysis_type", "bundle_uuid", "workflow_name", "workflow_version", "workflow_outputs"],
                                        "properties": {
                                            "analysis_type": {
                                                "type": "string"
                                            },
                                            "bundle_uuid": {
                                                "type": "string"
                                            },
                                            "workflow_name": {
                                                "type": "string"
                                            },
                                            "workflow_version": {
                                                "type": "string"
                                            },
                                            "workflow_outputs": {
                                                "type": "array",
                                                "items": {
                                                    "type": "object",
                                                    "required": ["file_path", "file_type"],
                                                    "properties": {
                                                        "file_path": {
                                                            "type": "string"
                                                        },
                                                        "file_type": {
                                                            "type": "string"
                                                        },
                                                        "file_uuid": {
                                                            "type": "string"
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

=== BD2KGenomics/dcc-metadata-indexer/output_metadata_7_20/86d41d05-824e-5d05-b605-498e41c8811f/metadata.json
{
    "center_name": "Stanford",
    "donor_uuid": "b121a26b-282c-5830-9084-c3b74bb56fc0",
    "program": "TEST",
    "project": "TEST",
    "schema_version": "0.0.2",
    "specimen": [
        {
            "samples": [
                {
                    "analysis": [
                        {
                            "analysis_type": "germline_variant_calling",
                            "bundle_uuid": "86d41d05-824e-5d05-b605-498e41c8811f",
                            "workflow_name": "germline-gatk",
                            "workflow_outputs": [
                                {
                                    "file_path": "sample_upload_files/germline.vcf",
                                    "file_type": "vcf"
                                }
                            ],
                            "workflow_version": "2.1.1"
                        }
                    ],
                    "sample_uuid": "d37e5c9a-1279-5734-b585-03beb045e544",
                    "submitter_sample_id": "S917367a1"
                }
            ],
            "specimen_uuid": "e56ca3d0-6d33-5537-bb58-c47ffca2ff9d",
            "submitter_specimen_id": "S917367a",
            "submitter_specimen_type": "Normal - blood derived"
        }
    ],
    "submitter_donor_id": "S917367",
    "timestamp": "2016-07-20T21:39:38.985679"
}

=== BD2KGenomics/dcc-metadata-indexer/output_metadata_merge_test/deduplication_testing/4032974374082734872/meta06.json
{
  "center_name": "Stanford",
  "donor_uuid": "b121a26b-282c-5830-9084-c3b74bb56fc0",
  "program": "TEST",
  "project": "TEST",
  "schema_version": "0.0.2",
  "specimen": [
    {
      "samples": [
        {
          "analysis": [
            {
              "analysis_type": "rna_seq_quantification",
              "bundle_uuid": "1485d032-df12-5d51-b7d3-7752a3bce7f3",
              "workflow_name": "rnaseq-cgl",
              "workflow_outputs": [
                {
                  "file_path": "sample_upload_files/gene_expression.rsem",
                  "file_type": "rsem"
                }
              ],
              "workflow_version": "3.2.1",
              "timestamp": "2016-07-20T21:39:38.985697"
            }
          ],
          "sample_uuid": "a8f34297-27a0-5609-bd62-0d8b8872dea2",
          "submitter_sample_id": "S917367b1"
        }
      ],
      "specimen_uuid": "fcd4a069-e881-59a1-a506-d8ec1071a9c8",
      "submitter_specimen_id": "S917367b",
      "submitter_specimen_type": "Primary tumour - solid tissue"
    }
  ],
  "submitter_donor_id": "S917367",
  "timestamp": "2016-07-20T21:39:38.985697"
}

=== BD2KGenomics/dcc-metadata-indexer/output_metadata_7_20/b50a1bf3-588a-5549-a104-1602e6d45f70/metadata.json
{
    "center_name": "Stanford",
    "donor_uuid": "0f1d53cb-9ef8-58ba-8db6-4eae42ee4316",
    "program": "TEST",
    "project": "TEST",
    "schema_version": "0.0.2",
    "specimen": [
        {
            "samples": [
                {
                    "analysis": [
                        {
                            "analysis_type": "germline_variant_calling",
                            "bundle_uuid": "b50a1bf3-588a-5549-a104-1602e6d45f70",
                            "workflow_name": "germline-gatk",
                            "workflow_outputs": [
                                {
                                    "file_path": "sample_upload_files/germline.vcf",
                                    "file_type": "vcf"
                                }
                            ],
                            "workflow_version": "2.1.1"
                        }
                    ],
                    "sample_uuid": "efd00a1d-604e-5e65-bf88-1c1464f14faa",
                    "submitter_sample_id": "S627291a1"
                }
            ],
            "specimen_uuid": "92511bd2-d5d8-51f4-8c0c-1cb53d54c6bf",
            "submitter_specimen_id": "S627291a",
            "submitter_specimen_type": "Normal - blood derived"
        }
    ],
    "submitter_donor_id": "S627291",
    "timestamp": "2016-07-20T21:39:38.985739"
}

=== BD2KGenomics/dcc-metadata-indexer/output_metadata_7_20/3a396d0d-fb5a-53de-9bd1-0a8d5249a233/metadata.json
{
    "center_name": "Stanford",
    "donor_uuid": "dc123cfd-6e09-5635-b81f-bce781244892",
    "program": "TEST",
    "project": "TEST",
    "schema_version": "0.0.2",
    "specimen": [
        {
            "samples": [
                {
                    "analysis": [
                        {
                            "analysis_type": "sequence_upload",
                            "bundle_uuid": "3a396d0d-fb5a-53de-9bd1-0a8d5249a233",
                            "workflow_name": "Sequence Uploader",
                            "workflow_outputs": [
                                {
                                    "file_path": "sample_upload_files/normal.fastq.gz",
                                    "file_type": "fastq"
                                }
                            ],
                            "workflow_version": "1.0.0"
                        }
                    ],
                    "sample_uuid": "942b29a5-d0f8-5a80-a3b1-e9a8a50363f5",
                    "submitter_sample_id": "S368291a1"
                }
            ],
            "specimen_uuid": "9a5a1dd7-7ed6-5c52-b86e-71c6e2d4a156",
            "submitter_specimen_id": "S368291a",
            "submitter_specimen_type": "Normal - blood derived"
        }
    ],
    "submitter_donor_id": "S368291",
    "timestamp": "2016-07-20T21:39:38.985880"
}

=== BD2KGenomics/dcc-metadata-indexer/output_metadata_7_20/cac0a22d-fb4c-5c6e-8c84-4f9d12ae3fc8/metadata.json
{
    "center_name": "Stanford",
    "donor_uuid": "5e6233fb-f193-59da-8102-b073a370a94f",
    "program": "TEST",
    "project": "TEST",
    "schema_version": "0.0.2",
    "specimen": [
        {
            "samples": [
                {
                    "analysis": [
                        {
                            "analysis_type": "sequence_upload",
                            "bundle_uuid": "cac0a22d-fb4c-5c6e-8c84-4f9d12ae3fc8",
                            "workflow_name": "Sequence Uploader",
                            "workflow_outputs": [
                                {
                                    "file_path": "sample_upload_files/normal.fastq.gz",
                                    "file_type": "fastq"
                                }
                            ],
                            "workflow_version": "1.0.0"
                        }
                    ],
                    "sample_uuid": "5d4f790c-e079-5f17-b9d7-f7d24a552a55",
                    "submitter_sample_id": "S191920a1"
                }
            ],
            "specimen_uuid": "67ecf138-52ef-5e6a-b96b-b41320209a5b",
            "submitter_specimen_id": "S191920a",
            "submitter_specimen_type": "Normal - blood derived"
        }
    ],
    "submitter_donor_id": "S191920",
    "timestamp": "2016-07-20T21:39:38.985527"
}

=== BD2KGenomics/dcc-metadata-indexer/output_metadata_7_20/b01b387f-ebc5-59d4-a2cb-7bf8eab61ea4/metadata.json
{
    "center_name": "Stanford",
    "donor_uuid": "1708baad-237f-58e3-adc6-ae46a23a9c71",
    "program": "TEST",
    "project": "TEST",
    "schema_version": "0.0.2",
    "specimen": [
        {
            "samples": [
                {
                    "analysis": [
                        {
                            "analysis_type": "sequence_upload",
                            "bundle_uuid": "b01b387f-ebc5-59d4-a2cb-7bf8eab61ea4",
                            "workflow_name": "Sequence Uploader",
                            "workflow_outputs": [
                                {
                                    "file_path": "sample_upload_files/tumor.fastq.gz",
                                    "file_type": "fastq"
                                }
                            ],
                            "workflow_version": "1.0.0"
                        }
                    ],
                    "sample_uuid": "6046a504-5b31-51dc-9713-f6d8c9e1519d",
                    "submitter_sample_id": "S176411b1"
                }
            ],
            "specimen_uuid": "1526b88a-2a13-5496-9030-50b17b5b6367",
            "submitter_specimen_id": "S176411b",
            "submitter_specimen_type": "Primary tumour - solid tissue"
        }
    ],
    "submitter_donor_id": "S176411",
    "timestamp": "2016-07-20T21:39:38.985593"
}

=== BD2KGenomics/dcc-metadata-indexer/output_metadata_7_20/6132a741-090d-5fb8-99d9-a68204843657/metadata.json
{
    "center_name": "Stanford",
    "donor_uuid": "088bda20-30d2-5944-a5fd-fee9a223f1a7",
    "program": "TEST",
    "project": "TEST",
    "schema_version": "0.0.2",
    "specimen": [
        {
            "samples": [
                {
                    "analysis": [
                        {
                            "analysis_type": "germline_variant_calling",
                            "bundle_uuid": "6132a741-090d-5fb8-99d9-a68204843657",
                            "workflow_name": "germline-gatk",
                            "workflow_outputs": [
                                {
                                    "file_path": "sample_upload_files/germline.vcf",
                                    "file_type": "vcf"
                                }
                            ],
                            "workflow_version": "2.1.1"
                        }
                    ],
                    "sample_uuid": "0c34704b-dd86-5141-aaf0-573656dee389",
                    "submitter_sample_id": "S123472a1"
                }
            ],
            "specimen_uuid": "03a781e4-e6a9-5d61-861e-49fcd034c5e4",
            "submitter_specimen_id": "S123472a",
            "submitter_specimen_type": "Normal - blood derived"
        }
    ],
    "submitter_donor_id": "S123472",
    "timestamp": "2016-07-20T21:39:38.985499"
}

=== BD2KGenomics/dcc-metadata-indexer/output_metadata_7_20/efd4540f-684f-5691-b1d7-acc36cf35a17/metadata.json
{
    "center_name": "Stanford",
    "donor_uuid": "1708baad-237f-58e3-adc6-ae46a23a9c71",
    "program": "TEST",
    "project": "TEST",
    "schema_version": "0.0.2",
    "specimen": [
        {
            "samples": [
                {
                    "analysis": [
                        {
                            "analysis_type": "alignment",
                            "bundle_uuid": "efd4540f-684f-5691-b1d7-acc36cf35a17",
                            "workflow_name": "bwa-mem-aligner",
                            "workflow_outputs": [
                                {
                                    "file_path": "sample_upload_files/normal.bam",
                                    "file_type": "bam"
                                }
                            ],
                            "workflow_version": "1.2.1"
                        }
                    ],
                    "sample_uuid": "2cdfdc6b-ea77-5392-88c5-d8ce7f9a6dd0",
                    "submitter_sample_id": "S176411a1"
                }
            ],
            "specimen_uuid": "bc441512-58bf-5662-ac7b-983315da1841",
            "submitter_specimen_id": "S176411a",
            "submitter_specimen_type": "Normal - blood derived"
        }
    ],
    "submitter_donor_id": "S176411",
    "timestamp": "2016-07-20T21:39:38.985600"
}
